name: 6666a

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Cloudflare Tunnel...
      run: |
        Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.msi -OutFile cloudflared.msi
        Invoke-WebRequest https://raw.githubusercontent.com/8ty/cloud/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/8ty/cloud/main/loop.bat -OutFile loop.bat
    - name: Downloading Launcher...
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/8ty/cloud/main/launcher/Node.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest https://raw.githubusercontent.com/8ty/cloud/main/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"
    - name: Installing Cloudflare Tunnel...
      run: msiexec /i cloudflared.msi /q
    - name: Connecting to your Cloudflare Tunnel Account...
      run: C:\Users\admin\cloudflared.exe service install $Env:CLOUDFLARE_TUNNEL_AUTH_TOKEN
      env:
        CLOUDFLARE_TUNNEL_AUTH_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_AUTH_TOKEN }}
    - name: Enabling Access...
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Creating Tunnel...
      run: cloudflared.exe tunnel create --url rdp://localhost:3389
    - name: Connect To Your host
      run: cmd /c start.bat
    - name: RDP Started Successfully! Now you can close the tab.
      run: cmd /c loop.bat
